# Generated by Django 4.1.7 on 2023-02-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TableManagement', '0003_alter_table_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='reserved',
            field=models.BooleanField(default=False),
        ),
    ]
