# Generated by Django 4.1.7 on 2023-02-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TableManagement', '0004_table_reserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
