# Generated by Django 4.1.7 on 2023-02-22 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TableManagement', '0005_alter_table_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='reserved',
        ),
    ]
