# Generated by Django 4.1.7 on 2023-02-21 15:54

import UserManagement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=4, primary_key=True, serialize=False, validators=[UserManagement.models.digitsOnly])),
                ('role', models.CharField(max_length=8)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
