# Generated by Django 4.1.7 on 2023-02-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('AD', 'admin'), ('EM', 'employee')], max_length=8),
        ),
    ]
