# Generated by Django 4.1.7 on 2023-02-21 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TableManagement', '0005_alter_table_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('seats', models.IntegerField()),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TableManagement.table')),
            ],
        ),
    ]
