# Generated by Django 4.1.7 on 2023-02-22 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationManagement', '0002_alter_reservation_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='seats',
        ),
    ]
